
spring.datasource.url=jdbc:mysql://<YOUR-RDS-ENDPOINT>:3306/erp_system?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=admin
spring.datasource.password=muskanbathla

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect

jwt.secret=591d62844abaececc787ec8a589e8f9ee42312fb64b92b12ad120dac8b43706b
jwt.expiration-ms=3600000

server.port=3000
